import ThemeRegistry from '@/customization/theme/ThemeRegistry'
import './styles/globals.css'
import './styles/anims.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/layout/header/Header'
import Footer from '@/components/layout/footer/Footer'

const inter = Inter({ subsets: ['latin', 'cyrillic'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet" />
      </head>
      <ThemeRegistry>
        <body className={inter.className + ' flex flex-col min-h-screen'}>
          <Header />
          <section className='flex-grow'>
            {children}
          </section>
          <Footer />
        </body>
      </ThemeRegistry>
    </html>
  )
}
